runtime: nodejs16

env_variables:
  NODE_ENV: "production"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
- url: /.*
  script: auto
  secure: always

env: flex

beta_settings:
  cloud_sql_instances: your-project:your-region:your-instance